name: Deploy to Production

on:
  deployment:
    types: [created]

jobs:
  deploy:
    if: github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.APP_URL }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run test
      - run: bun run build

      - name: Apply D1 migrations
        run: |
          bunx wrangler d1 migrations apply DB --env=production \
            --account-id=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} \
            --token=${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Pages (production)
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=${{ vars.PROJECT_NAME }} --branch=main --env=production

      - name: Sync R2 Assets
        if: ${{ vars.SHOULD_SYNC_R2 == 'true' }}
        run: |
          bunx wrangler r2 object put ASSETS --file=./static --env=production

      - name: Mark deployment as successful
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          deployment_id: ${{ github.event.deployment.id }}
